// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  TRANSLATE_CACHE: KVNamespace;
  DASHSCOPE_API_KEY: string;
}
