name = "translate"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# XAI_API_KEY will be set in the Cloudflare dashboard or via wrangler secret
DASHSCOPE_API_KEY = 'sk-68ada9b0d2654e35bc94130d347550f6'

[[rules]]
type = "ESModule"
globs = ["**/*.ts"]

[[kv_namespaces]]
binding = "TRANSLATE_CACHE"
id = "bd1cf0dd685146d8b991bed03c8a62f2"