name = "article-extractor"
main = "src/index.ts"
compatibility_date = "2024-03-11"

[vars]
# Add any environment variables here if needed

[[r2_buckets]]
binding = "ARTICLES_BUCKET"
bucket_name = "english-reader"